# Generated by Django 5.1.5 on 2026-05-07 11:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MD', 'Managing Director'), ('HR', 'Human Resources'), ('DEPT_HEAD', 'Department Head'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_user',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Department center latitude for GPS geofence', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Department center longitude for GPS geofence', max_digits=9, null=True)),
                ('is_cinema', models.BooleanField(default=False, help_text='Cinema departments are exempt from late penalties')),
                ('work_days', models.CharField(default='0,1,2,3,4,5', help_text='Comma-separated work days: 0=Mon,1=Tue,...,6=Sun', max_length=50)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated IP addresses for desktop attendance')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MD', 'DEPT_HEAD']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='Auto-generated employee ID (e.g., wolan Hr-CIN-001)', max_length=20, unique=True)),
                ('personal_account', models.CharField(blank=True, help_text='Personal bank account (probation salary)', max_length=30)),
                ('salary_account', models.CharField(blank=True, help_text='Salary bank account (permanent salary)', max_length=30)),
                ('docs_vault', models.JSONField(blank=True, default=dict, help_text='Document storage: academic, ID, experience, salary slips, photo')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after HR verification — no re-upload allowed')),
                ('probation_status', models.CharField(choices=[('PROBATION', 'Probation'), ('PERMANENT', 'Permanent'), ('TERMINATED', 'Terminated')], default='PROBATION', max_length=20)),
                ('aadhaar_masked', models.CharField(blank=True, help_text='Masked Aadhaar: XXXXXXXX1234 format only', max_length=12)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(default=30, help_text='Hardcoded 1-month notice for all employees')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly basic salary', max_digits=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_employee_profile',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROFILE_CREATED', 'Profile Created'), ('PROFILE_LOCKED', 'Profile Locked'), ('PROFILE_UPDATED', 'Profile Updated'), ('DOC_UPLOADED', 'Document Uploaded'), ('DOC_VERIFIED', 'Document Verified'), ('ATTENDANCE_IN', 'Clock In'), ('ATTENDANCE_OUT', 'Clock Out'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('INCENTIVE_ADDED', 'Incentive Added'), ('PAYROLL_GENERATED', 'Payroll Generated'), ('PAYROLL_FINALIZED', 'Payroll Finalized'), ('SALARY_CHANGED', 'Salary Changed'), ('STATUS_CHANGED', 'Status Changed'), ('TERMINATED', 'Terminated'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details as JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.employeeprofile')),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('face_image_path', models.CharField(blank=True, help_text='Path to face capture image (webcam verification)', max_length=500)),
                ('is_valid', models.BooleanField(default=True, help_text='False if geofence/IP validation failed')),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('MOBILE', 'Mobile (GPS)'), ('DESKTOP', 'Desktop (IP+Face)'), ('MANUAL', 'Manual Entry')], default='MOBILE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='core.employeeprofile')),
            ],
            options={
                'db_table': 'core_attendance',
                'ordering': ['-date', '-in_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('is_public', models.BooleanField(default=True, help_text='Public holiday (auto-fetched) vs custom')),
                ('is_active', models.BooleanField(default=True, help_text='HR can deactivate holidays (e.g., remove Buddha Purnima)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='If empty, applies to all departments', to='core.department')),
            ],
            options={
                'db_table': 'core_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_type', models.CharField(choices=[('PROJECT_INHOUSE', 'Project In-House'), ('PROJECT_CLIENT', 'Project Client'), ('WEEKEND_SAT', 'Weekend Sales (Saturday)'), ('WEEKEND_SUN', 'Weekend Sales (Sunday)'), ('ORDERS_VOLUME', 'Orders Volume'), ('CUSTOM', 'Custom')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('visuals_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage visual indicator', max_digits=5)),
                ('month', models.DateField(help_text='Month this incentive applies to (1st of month)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Only MD can create incentives', limit_choices_to={'role': 'MD'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_incentives', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incentives', to='core.employeeprofile')),
            ],
            options={
                'db_table': 'core_incentive',
                'ordering': ['-month', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='core.employeeprofile')),
            ],
            options={
                'db_table': 'core_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Payroll month (1st of month)')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('working_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('late_deduction_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('ot_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('incentive_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pt_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kerala Professional Tax slab', max_digits=8)),
                ('esi_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('deduction_notes', models.TextField(blank=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HEAD_REVIEW', 'Head Review (48h)'), ('HR_APPROVED', 'HR Approved'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='Immutable once locked/finalized')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='core.employeeprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_payroll',
                'ordering': ['-month'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['department', 'probation_status'], name='core_employ_departm_8dc406_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active', 'department'], name='core_employ_is_acti_d55576_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_audit__timesta_9f170b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['profile', '-timestamp'], name='core_audit__profile_0a522b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_audit__action_a453b1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'profile'], name='core_attend_date_0355c0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['profile', '-in_time'], name='core_attend_profile_31cde8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_late', 'date'], name='core_attend_is_late_93f378_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('profile', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('profile', 'month')},
        ),
    ]
