# Generated by Django 6.0.5 on 2026-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_department_head_alter_user_role_stafftask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='probation_status',
            field=models.CharField(choices=[('PROBATION', 'Probation'), ('PERMANENT', 'Permanent'), ('TERMINATED', 'Terminated'), ('TRAINEE', 'Trainee'), ('INTERN', 'Intern')], default='PROBATION', max_length=20),
        ),
    ]
