# Generated by Django 6.0.5 on 2026-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employeeprofile_probation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('CASUAL', 'Casual Leave'), ('EMERGENCY', 'Emergency')], max_length=20),
        ),
    ]
